kinoticketing/ui

- src/routes/+layout.svelte
- Closes #25 
when resizing the window or viewing the website on mobile, the elements dynamically reposition themselves
> Make layout responsive

- src/routes/movies/[id]/+page.server.ts
- src/routes/movies/[id]/+page.svelte
The detail page for each movie looks better now. It also includes a list of all showtimes (Time, Hall No. and duration). The goal is to make the showtimes clickable and then to book a ticket.
Closes #24
> movies detail page

- src/routes/+layout.svelte
changed the layout so that the navbar and footer act responsive on different window sizes.
Closes #42
> feat: layout is responsive now

- src/routes/+layout.svelte
Improved behavior of the navbar when decreasing the screens width while still implementing okans first approach.
Schaut euch gerne mal an was ich da verbrochen hab, bin nicht böse wenn es euch nicht gefällt 😂 
Zum jetzigen Zeitpunkt funktioniert meine Version komplett, ohne dass neue Sachen von euch überschrieben werden. Also falls conflicts auftreten, könnte meine Version komplett übernommen werden. Die vielen Änderungen kommen von formatierten code von svelte formatter in VS Code. Man kann ja die Version von mir anschauen, ohne zu mergen.
> Adjust navbar to different screen sizes jan

- src/routes/admin/manage-halls/[hall_id]/+page.server.ts
- src/routes/admin/manage-halls/[hall_id]/+page.svelte
- src/routes/admin/manage-screenings/[showtime_id]/+page.server.ts
- src/routes/admin/manage-screenings/[showtime_id]/+page.svelte
i implemented the detail pages for halls and showtimes. screenshots can be found below. in the future there should be an option to edit the title, movie and seating plan.
for the seating plan to be editable, we should fix our database first :)
Closes #49
> Detail page for halls and showtimes admin

- src/hooks.server.ts
- src/lib/auth.ts
- src/routes/+layout.svelte
- src/routes/auth/login/+page.server.ts
I fixed the drop down menu visually, but more importantly according to the session to display an "account" or a "sign in" button.
Fixes #57
> fix: dropdown session adapted

- package-lock.json
- package.json
- src/lib/neonAdapter.ts
- src/routes/api/maps/+server.ts
- src/routes/api/user/address/+server.ts
- src/routes/auth/account/+page.svelte
implemented address functionality in ui and backend with db read/ write.
Fixes #59
> feat: address functionality implemented

- src/routes/admin/manage-screenings/create-screening/+page.svelte
- src/routes/admin/manage-screenings/create-screening/save-movie/+server.ts
when creating a screening, new relation movie gets used and movies are saved to the database table 'movies'
Fixes #70
> load movies into db

- src/lib/auth.ts
- src/lib/types/paypal.d.ts
- src/routes/api/checkout/+server.ts
- src/routes/api/payments/[payment_id]/paypal/capture/+server.ts
- src/routes/api/payments/[payment_id]/paypal/create/+server.ts
- src/routes/checkout/[payment_id]/+page.server.ts
- src/routes/checkout/[payment_id]/+page.svelte
- src/routes/checkout/[payment_id]/success/+page.server.ts
- src/routes/checkout/[payment_id]/success/+page.svelte
added complete payment functionallity, ticket creation, booking/ checkout/ success page
added mutual exlusion
Fixes #74
> feat: payment, tickets, booking page, checkout page, success page

- src/routes/admin/manage-halls/+page.server.ts
- src/routes/admin/manage-halls/+page.svelte
- src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
- src/routes/admin/manage-screenings/[screening_id]/+page.svelte
Mainly, I fixed the detail page for screenings, however:
- deleting a hall now needs confirmation
- the detail page shows the seating plan correctly
- the capacity of EVERY seatplan is correct now
Fixes #83
> fix admin screening detail page

- src/routes/admin/manage-halls/+page.svelte
- src/routes/admin/manage-halls/[hall_id]/+page.svelte
- src/routes/admin/manage-halls/create-hall/+page.svelte
- src/routes/admin/manage-reservations/+page.server.ts
- src/routes/admin/manage-reservations/+page.svelte
- src/routes/admin/manage-reservations/[id]/+page.server.ts
- src/routes/admin/manage-reservations/[id]/+page.svelte
- src/routes/admin/manage-screenings/+page.svelte
- src/routes/admin/manage-screenings/[screening_id]/+page.svelte
- src/routes/admin/manage-screenings/create-screening/+page.svelte
Full implementation of /admin/manage-reservations page including a detail page and cancelling a ticket (screenshots below). Also added a 'Back' button to each page in order to navigate back.
Fixes #87
> feat: admin implement manage reservations

- src/app.d.ts
- src/hooks.server.ts
- src/routes/+layout.svelte
- src/routes/api/reservations/[id]/cancel/+server.ts
- src/routes/api/user/reservations/+server.ts
- src/routes/auth/account/+page.svelte
- src/routes/auth/login-success/+page.server.ts
- src/routes/auth/login-success/+page.svelte
- src/routes/auth/login/+page.svelte
- src/routes/reservations/+page.server.ts
- src/routes/reservations/+page.svelte
EVERYTHING, ui changes throughout the application, routing optimization, reservation page with cancel function, different pages adjusted newly styled.
Fixes #94
> UI updates to footer, UI and functionality updates to reservations page, account page

- package-lock.json
- package.json
- src/lib/util/qrCode.ts
- src/routes/checkout/[payment_id]/success/+page.svelte
Added a utility to generate unique qr codes for the tickets. Also the qr codes will automatically be displayed after the tickets are bought.
Fixes #80
> Qrcode für tickets

- src/routes/reservations/+page.svelte
qr code is now available in reservations, they additionally are now sorted by status, first confirmed -> pending -> cancelled, no qr code visible when cancelled or pending
Fixes #101
> feat: qr code visible in reservations

- src/routes/admin/+page.svelte
- src/routes/admin/manage-halls/+page.server.ts
- src/routes/admin/manage-halls/+page.svelte
- src/routes/admin/manage-halls/[hall_id]/+page.svelte
- src/routes/admin/manage-halls/create-hall/+page.svelte
- src/routes/admin/manage-reservations/+page.svelte
- src/routes/admin/manage-screenings/+page.server.ts
- src/routes/admin/manage-screenings/+page.svelte
- src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
- src/routes/admin/manage-screenings/[screening_id]/+page.svelte
- src/routes/admin/manage-screenings/create-screening/+page.svelte
- src/routes/movies/[id]/+page.server.ts
- src/routes/movies/[id]/+page.svelte
- updated the entire ui to follow the styling of other pages
- added preview of seatplan and movie poster to tiles
- the admin is Herrscher now :)
Closes #96
> feat: revamp admin section

- src/routes/contact/+page.svelte
- src/routes/faq/+page.svelte
- src/routes/privacy/+page.svelte
- src/routes/terms/+page.svelte
This pull request includes the addition of new pages for the contact form, FAQ, privacy policy, and terms of service. The changes primarily focus on implementing the functionality and styling for these pages.
New Pages:
* [`src/routes/contact/+page.svelte`](diffhunk://#diff-a3ce569c85a82e542597e78425a11f9a53d5f2d6b2d2393a09690d6b1dcce604R1-R262): Added a contact form with form validation, submission handling, and success/error messages. The page also includes contact details and an embedded Google Map.
* [`src/routes/faq/+page.svelte`](diffhunk://#diff-7fcaa7a1627823bcde6e170b7f2ba33f4d4614e5e17e7b898291f5054dfeaa18R1-R170): Implemented an FAQ section with an accordion-style interface for displaying questions and answers.
* [`src/routes/privacy/+page.svelte`](diffhunk://#diff-8d3471e04ae62 …
> feat: footer links

- src/app.d.ts
- src/hooks.server.ts
- src/lib/stores/adminAuth.ts
- src/routes/+layout.svelte
- src/routes/admin/+layout.server.ts
- src/routes/admin/login/+page.server.ts
- src/routes/admin/login/+page.svelte
This pull request introduces an admin authentication system to the application. The key changes include the addition of admin authentication handlers, creation of an admin authentication store, updates to the layout to include admin access links, and the implementation of admin login functionality.
Admin authentication implementation:
* [`src/hooks.server.ts`](diffhunk://#diff-b5aa13ce0a61c3f166000471d0729aa6a8e57292fdbd8d88452443502e4b9a4aR1-R42): Added `adminHandle` to manage admin authentication and updated the sequence of handlers to include `adminHandle`.
* [`src/lib/stores/adminAuth.ts`](diffhunk://#diff-bc5c5e57b6fa9d75e7b842c0cf1797facbc0290854923d2a48cc0df203883066R1-R30): Created an admin authentication store that manages admin login and logout states using `localStorage`. …
> feat: admin routes protected 

- src/routes/admin/manage-halls/[hall_id]/+page.server.ts
- src/routes/admin/manage-halls/[hall_id]/+page.svelte
- src/routes/admin/manage-halls/[hall_id]/+server.ts
- src/routes/admin/manage-halls/[hall_id]/admin.manage-halls.[hall_id].server.test.ts
This pull request includes multiple changes to the hall management functionality in the `src/routes/admin/manage-halls/[hall_id]` directory. The key changes involve updating the hall data loading process, adding a new endpoint for updating hall information, and modifying the test cases to reflect these updates. The admin can now edit the title and seat plan for each hall.
* `src/routes/admin/manage-halls/[hall_id]/+page.server.ts`: Modified the `load` function to exclude `total_columns` from the hall data query and added logic to count seats per row. Updated the seat plan creation to use an object for row sizes and a nested array for the seat plan. ([src/routes/admin/manage-halls/[hall_id]/+page.server.tsL20-R23](diffhunk://#diff-3929372798f87fa818a9b4bfe97147f997d8c338364ea010314fbe5b3190 …
> add edit mode for halls in admin-tool

- src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
- src/routes/admin/manage-screenings/[screening_id]/+page.svelte
- src/routes/admin/manage-screenings/[screening_id]/+server.ts
- src/routes/admin/manage-screenings/[screening_id]/admin.manage-screenings.[screening_id].server.test.ts
This pull request includes significant changes to the management of screenings in the admin interface. The most important changes include refactoring the database queries, adding the ability to update screenings, and enhancing the user interface for editing screenings.
* `src/routes/admin/manage-screenings/[screening_id]/+page.server.ts`: Refactored database queries for loading screenings and halls, and removed outdated comments. ([src/routes/admin/manage-screenings/[screening_id]/+page.server.tsL23-L191](diffhunk://#diff-a8db813aa83fe1ffa45a165a0fa924b0718abf9ded45bf737ebb2f562079d868L23-L191))
* `src/routes/admin/manage-screenings/[screening_id]/+server.ts`: Added a PUT endpoint to handle updates to screenings, including validation and updating the screening's details. …
> feat: admin edit screenings

- src/routes/admin/manage-reservations/+page.svelte
@Gree44 opened the issue #129 explaining that the reservations table doesn't get shown completely (regarding its width). I now fixed it to be shown entirely and to be responsive (scrollable) when shrinking the window.
This pull request includes several changes to improve the styling and layout of the reservations management page in the `src/routes/admin/manage-reservations/+page.svelte` file. The changes focus on enhancing the table's appearance, responsiveness, and usability.
Styling and layout improvements:
* Added a `ticket-code` class to the "Ticket Code" column for better word wrapping and breaking. [[1]](diffhunk://#diff-37cd4876945933d2544e756627293308a3a9ab90504f5d8339654c0316a55657L50-R50) [[2]](diffhunk://#diff-37cd4876945933d2544e756627293308a3a9ab90504f5d8339654c0316a55657L66-R …
> Fix reservations table

- src/routes/admin/manage-halls/+page.svelte
- src/routes/admin/manage-halls/create-hall/+page.svelte
- src/routes/admin/manage-screenings/create-screening/+page.svelte
- src/routes/movies/[id]/+page.svelte
This pull request includes several changes to improve the user experience and functionality of the admin and movie pages. The most important changes include adding new seat types, enhancing the screening creation process with a step-by-step interface, and improving error messaging for trailers.
Enhancements to seat types and hall management:
* [`src/routes/admin/manage-halls/create-hall/+page.svelte`](diffhunk://#diff-4635ebabfa999d9f559cb01f8e479639d31391684a966ff42414c6180df2084cL13-R13): Added a new seat type 'Premium' and updated the styles for premium seats. [[1]](diffhunk://#diff-4635ebabfa999d9f559cb01f8e479639d31391684a966ff42414c6180df2084cL13-R13) [[2]](diffhunk://#diff-4635ebabfa999d9f559cb01f8e479639d31391684a966ff42414c6180df2084cR444-R448)
Enhancements to screening creation: …
> polishing work

- package-lock.json
- package.json
- src/lib/auth.ts
- src/routes/auth/login/+page.server.ts
- src/routes/auth/login/+page.svelte
- src/routes/auth/login/types.ts
- src/routes/auth/register/+page.server.ts
- src/routes/auth/register/+page.svelte
- src/routes/auth/register/server.test.ts
This pull request introduces several changes to enhance the authentication and registration functionality, as well as updates to dependencies and scripts in the project. The most important changes include the addition of credentials-based authentication, updates to the login and registration pages, and modifications to the `package.json` file.
* [`src/lib/auth.ts`](diffhunk://#diff-486994d46df34c53636a706a1ca6a05bd8261ccde47463ea2c739af56f090b78R2-R138): Added credentials-based authentication using email and password, including bcrypt for password hashing and a PostgreSQL connection for user verification.
* [`src/routes/auth/login/+page.server.ts`](diffhunk://#diff-3e29680c34d69042792627749dc431e54ba3b913f116b0d2022f2b1b270ce514R17-R59): Added form handling for login with email and …
> feat: Password login
